name: Build and Push Light Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push deps
        run: |
          docker build --target=deps \
            -t ghcr.io/${{ github.repository }}:deps \
            --cache-to=type=inline \
            .
          docker push ghcr.io/${{ github.repository }}:deps

      - name: Build and push full app
        run: |
          docker build \
            --cache-from=type=registry,ref=ghcr.io/${{ github.repository }}:deps \
            -t ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }} \
            .
          docker push ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}
